parcelRequire = function (e, r, t, n) { var i, o = "function" == typeof parcelRequire && parcelRequire, u = "function" == typeof require && require; function f(t, n) { if (!r[t]) { if (!e[t]) { var i = "function" == typeof parcelRequire && parcelRequire; if (!n && i) return i(t, !0); if (o) return o(t, !0); if (u && "string" == typeof t) return u(t); var c = new Error("Cannot find module '" + t + "'"); throw c.code = "MODULE_NOT_FOUND", c } p.resolve = function (r) { return e[t][1][r] || r }, p.cache = {}; var l = r[t] = new f.Module(t); e[t][0].call(l.exports, p, l, l.exports, this) } return r[t].exports; function p(e) { return f(p.resolve(e)) } } f.isParcelRequire = !0, f.Module = function (e) { this.id = e, this.bundle = f, this.exports = {} }, f.modules = e, f.cache = r, f.parent = o, f.register = function (r, t) { e[r] = [function (e, r) { r.exports = t }, {}] }; for (var c = 0; c < t.length; c++)try { f(t[c]) } catch (e) { i || (i = e) } if (t.length) { var l = f(t[t.length - 1]); "object" == typeof exports && "undefined" != typeof module ? module.exports = l : "function" == typeof define && define.amd ? define(function () { return l }) : n && (this[n] = l) } if (parcelRequire = f, i) throw i; return f }({
    "vkct": [function (require, module, exports) {
        module.exports = "../assets/01_landing/landing-banner-mobile.mp4";
    }, {}], "lLBS": [function (require, module, exports) {
        module.exports = "../assets/01_landing/landing-banner-cropped.mp4";
    }, {}], "QvaY": [function (require, module, exports) {
        "use strict"; var e = r(require("../assets/01_landing/landing-banner-mobile.mp4")), n = r(require("../assets/01_landing/landing-banner-cropped.mp4")); function r(e) { return e && e.__esModule ? e : { default: e } } function i() { return window.matchMedia("(max-width: 521px)").matches } function d() { for (var r = document.querySelectorAll("video.homepage__video--header"), d = 0; d < r.length; d++)i() ? r[d].src = e.default : r[d].src = n.default } var a = i(); window.addEventListener("resize", function () { var e = i(); e !== a && d(), a = e }), d();
    }, { "../assets/01_landing/landing-banner-mobile.mp4": "vkct", "../assets/01_landing/landing-banner-cropped.mp4": "lLBS" }]
}, {}, ["QvaY"], null)
//# sourceMappingURL=/responsive-banner.js.map